USE food_chat_db;
DROP TABLE IF EXISTS dish;
DROP TABLE IF EXISTS menu;
DROP TABLE IF EXISTS hoursAvailable;
DROP TABLE IF EXISTS foodType;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS restaurant;